name: buildAgentDockerFile

on:
  push:
    branches: [ "EzzOps/DevopsPipelines" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ezzops/mis-build-agent:${{ github.sha }}
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure kubectl
        env:
          MY_SECRET: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          mkdir $HOME/.kube/
          echo $KUBE_CONFIG_DATA | base64 --decode > $HOME/.kube/config/kubeconfig.yaml
          sudo chown $USER:$USER $HOME/.kube/config
          kubectl config use-context default
    

      - name: Deploy pod
        run: |
          - name: Deploy pod
            run: |
              kubectl create pod --image=ezzops/mis-build-agent


