name: buildAgentDockerFile

on:
  push:
    branches: [ "EzzOps/DevopsPipelines" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ezzops/mis-build-agent:${{ github.sha }}
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary version
        # Arguments
        # command – required: The command you want to run, without kubectl, e.g. get pods
        
        # config – required: A base64-encoded kubeconfig file with credentials for Kubernetes to access the cluster. You can get it by running the following command:
        
        # cat $HOME/.kube/config | base64
        # version: The kubectl version with a 'v' prefix, e.g. v1.21.0. It defaults to the latest kubectl binary version available.
        
        # binaries-url: The url to download the binaries from. It defaults to the official release page if empty.         
          
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image --record deployment/my-app container=ezzops/mis-build-agent:${{ github.sha }}

