name: buildAgentDockerFile

on:
  push:
    branches: [ "EzzOps/DevopsPipelines" ]
  workflow_dispatch:

env:
  MY_VARIABLE: "apiVersion: v1 clusters: - cluster: certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTURJd05qZzNNREl3SGhjTk1qTXhNakE0TWpBMU1UUXlXaGNOTXpNeE1qQTFNakExTVRReQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTURJd05qZzNNREl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTWTE5NDB0dlBORnljZWNsTmZnTkEyVEQvUWtMU0xaRWJVRCtLRjg3aVYKUmd4VTFaeW1qQlQ1TDY5cGpuZUFEcC92VUY4d21icjVGWThTQkhxSzVzTUNvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUdlR3lsdUVaMk1yOHE2cWtjU1hqCk1ZbmppekV3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnSUpVOXVqTUFrZEYxcHhmbWk4UHhuVE1ZZDl1a2dNLzIKQS9DcjZLL2lwYzBDSVFDZGZmK0hkZXlmYzk5STMvQnp5STZ3WGh1dWdHOXlnc1V2YTVYWHNZZ2t1QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K server: http://88b8-197-135-72-167.ngrok-free.app/ name: default contexts: - context: cluster: default user: default name: default current-context: default kind: Config preferences: {} users: - name: default user: client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJWnFGcHBjMzJHNWN3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOekF5TURZNE56QXlNQjRYRFRJek1USXdPREl3TlRFME1sb1hEVEkwTVRJdwpOekl3TlRFME1sb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJKbFlJeUtqUUJudUFjWVkKcHpEZUNzeGxOcng2ek5xQWhiSktuM0lqRklJTXFIa1hCd2hQWnNUNU9udVFqcEgzQ0dLUWsybkNnbW1nekVyOQpXcW5WNkQralNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCVGo3ZnZrMnVtYmY2ckxjQndjWGY5SnJyOTduakFLQmdncWhrak9QUVFEQWdOSkFEQkcKQWlFQTVSN0I3U2RWTWpKVEVFWkxjUzFXQkt1UWFGVTBVVE9GekNiS0pqbE00OTBDSVFDci9SV1diRFBTYXZmQwpVb252U3dJYkp1aHdHMG5waUQwYURENGMxRDlucWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZHpDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwClpXNTBMV05oUURFM01ESXdOamczTURJd0hoY05Nak14TWpBNE1qQTFNVFF5V2hjTk16TXhNakExTWpBMU1UUXkKV2pBak1TRXdId1lEVlFRRERCaHJNM010WTJ4cFpXNTBMV05oUURFM01ESXdOamczTURJd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBU3AvUVZwNlN3SitHWE9vVjVoUE5XRllMY2JYZ21vMmUrNTRXaVppOTVaCnppbmViVFN4WS95bnJQOGhVTFRjekdPc2FoVGIwQmRYaXJuRTBmTFpuS0hBbzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVU0KzM3NU5ycG0zK3F5M0FjSEYzLwpTYTYvZTU0d0NnWUlLb1pJemowRUF3SURTQUF3UlFJZ1FSaTRtNlp2TmxtWWVEUXpqenplR1ZneHU3ZjRicTdHCk9jN1lrTU1FWkFrQ0lRRGdwS09mczdYQm1BeXQ1eU1CYnk5YkU4Qm55K085bHczUURyenZTeXpvK2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQo="

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ezzops/mis-build-agent:${{ github.sha }}
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3  
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure kubectl
        run: |
            mkdir -p $HOME/.kube
            cp config $HOME/.kube/config
            sudo chown $USER:$USER $HOME/.kube/config

      - name: Deploy pod
        run: |
           kubectl run githubRunner --image=ezzops/mis-build-agent


